kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: mcr.microsoft.com/playwright:v1.17.1-focal
    commands:
      - apt update
      - apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - git clone --branch main https://github.com/alextaygeeyang/prometheus_oracle.git
      - cd /prometheus_oracle
      - npm ci
      - npm test
