kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: mcr.microsoft.com/playwright:v1.17.1-focal
    commands:
      - git clone --branch main https://github.com/alextaygeeyang/prometheus_oracle.git
      - git checkout $DRONE_COMMIT
      - cd prometheus_oracle
      - npm ci
      - npm test
trigger:
  branch:
    - dev-ci
