version: "3"
services:
  drone-server:
    container_name: drone-server
    image: drone/drone:latest
    ports:
      - 25555:80
    volumes:
      - db-data:/var/lib/drone/
    restart: always
    environment:
      # - DRONE_OPEN=false
      - DRONE_SERVER_HOST=cc85-115-135-30-111.ngrok.io # tunnel hostname
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_ADMIN=alextay96
      - DRONE_GITHUB_CLIENT_ID=f4ae3fc2db3b08533aa4
      - DRONE_GITHUB_CLIENT_SECRET=cd7491dfa51e764443cd52f2bb0239e572022f0a
      - DRONE_SERVER_PROTO=http # tunnel adds https on top
      - DRONE_RPC_SECRET=75a4acae5a89382b5b6d51d671880cf4
    expose:
      - 25555
  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker
    restart: always
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server:25555
      - DRONE_RPC_SECRET=75a4acae5a89382b5b6d51d671880cf4
      - DRONE_RUNNER_CAPACITY=4
volumes:
  db-data:
