version: "3.8"

services:
  worker:
    build: .
    tty: true
    networks:
      prometheus_oracle_network:
        ipv4_address: 172.78.0.33
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:13.0-alpine
    networks:
      prometheus_oracle_network:
        ipv4_address: 172.78.0.44
    volumes:
      - prometheus_oracle_postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=oracle_alextay
      - POSTGRES_PASSWORD=oracle_alextay
      - POSTGRES_DB=prometheus_oracle
    expose:
      - 5432
    container_name: prometheus_oracle_postgres

volumes:
  prometheus_oracle_postgres:

networks:
  prometheus_oracle_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.78.0.0/24
